#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Bluebook
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/tldr/chenla-bluebook/bluebook.org
  :Created:   2017-06-07T15:35@Prek Leap (11.642600N-104.919210W)
  :ID:        a043e6f1-ec8a-4d60-af71-ad54ee012fed
  :VER:       550096596.118544686
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:QIC6-1753
  :Class:     deploy
  :Type:      tldr
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-tl;dr-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib


* First Admonition

What you are holding in your hand distills what we are doing as far as
it can be distilled without loosing so much context that it becomes
meaningless.  Anyone who thinks that large complex things can be
boiled down to a dark greaser smear in a couple of paragraphs, a table
and a couple of charts is delusional.  The greasy smear approach,
which is commonly called an /elevator pitch/ might be appropriate to
explain an iteration on an existing idea.  But fails totally when
describing a non-incremental innovation.  This is not a pitch, it's an
overview of foundational work that we are building a number of
commercial and not-for-profit projects on.

* 1

In the structure of scientific revolutions, Kuhn describes science as
being a progression of different paradigms.  A paradign is a nebulous
assemblage of recorded observations, theories, best practices and
information that share a common vocabulary and structure that science
is done in.  Over time, new observations that break the paradigm begin
to build up until the paradigm is broken and everyone scrambles to
come to a consensus around a new paradigm that better explains the
evidence.  This is a useful way of understanding a very wide range of
human activity from government, to business, education and the arts.

* 2

In the structure of scientific revolutions, Kuhn describes science as
being a progression of different paradigms.  A paradign is a nebulous
assemblage of recorded observations, theories, best practices and
information that share a common vocabulary and structure that science
is done in.  Over time, new observations that break the paradigm begin
to build up until the paradigm is broken and everyone scrambles to
come to a consensus around a new paradigm that better explains the
evidence.  This is a useful way of understanding a very wide range of
human activity from government, to business, education and
the arts.

* 3

Our civilization is at the very end of a paradigm that has been in
place since the end of the World War II.  But the number of anomolies
have now piled up to the point where we are now reaching a critical
threshold just before the paradigm shatters and needs to be replaced.
That period of scrambling around trying to find a new consensus is not
only messy but a potentially dangerous time to be alive.  Very bad
things happen, because most people will spend all of their energy
trying to salvage the paradigm rather than let it go and move on.
Climate-change denial, extreme nationalistim, poplulism and
straight-out fascism is suddenly attractive to a large number of
people who are threatened as the decaying paradigm collapses.  At the
same time, such times are exciting to live through, whole new worlds
become possible that would have been dismissed as impractical or even
impossible a few years before.  We live in interesting times, and for
many that is a bad thing.  But for some, it is liberating and
exhilerating.  This is the time to identity and place bets on those
people, not the timorous Luddites cowering in the shadows praying for
a return of a golden past that never existed.

* 4

Now is the time to go back to first principles and understand who we
are, how we got to where we are and where things are headed in order
to understand how things need the change and what needs to be be built
that will eventually become part of the new consensus.  This is
exactly what we have been working on for twenty years.  We don't need
to play catch-up because we started work on this back when the cracks
were getting large enough in the dike to realise the inevitibility of
the dike's collapse.  It's only been in the past 18 months that it is
now clear that the collapse is now imminent and through the cracks
which have widened to become gaping rents to see the shape of what
lies beyond.  As yet these are still shapes.  We know that what is now
inevitable but we still don't know the final form they will take.
We're just starting to look for solutions that we can all agree on.

* 5

All species, plant, insect, animal or microbial evolve to fill a
specific niche in an ecosystem, full stop, no exceptions.  Keep in
mind that an ecosystem is a system.  Systems are made up of different
parts that must work together for the system to keep running.  Again,
no exceptions.  Homo Sapiens is a species of hominid that evolved to
fill a niche in the African savannah ecosystem.  When we spread beyond
the savannah and eventually over the entire planet, we had to take
enough of the savannah with us to survive.  Things like clothes,
cooked food, and shelter all helped us to adapt to climates we were
not designed to live in.  That ability to dynamically adapt in real
time is what sets us apart from other species.  We are not bound by
the hardcoded instincts that comes with a limbic system.  Our
freakishly large cerebral cortex can be thought of as a general
purpose programable computer.

* 6

Civilization emerged from the agricultural revolution as settlements
grew larger in size and complexity than nomadic social structures
could maintain.  Humans did not evolve to live in herds.  We are pack
animals, fleet of foot and able to think on our feet.  Packing each
other into close quarters with no chance to escape each other is not
the niche we evolved to fill.

If pressed, I would say that if you had to pick a single thing that
goes to the root of all of mankind's problems, that would have to be
the problem of scale.  Everything that Man has done that is good, as
well as everything we have done that is bad can be understood as a
scaling problem.

* 7

Humans have a very small amount of working memory.  We can only keep
at the most, three things on working memory at a time.  Our short term
memory is slightly larger which is expressed as the magic number seven
plus or minus two.  Recent research indicates that the number is
closer to for or five.  We can only maintain relationships with a
maximum of 150 people, what is known as Dunbar's number.  This means
we are able to related to people less and less as a group, communitiy
or organizations increases in size.  We can only maintain close
relationships with a handful of people, topping out at fourteen or
less.  These are the numbers that we must stay within when we design
buildings, businesses and governments.  The story of civilization is
the story of how we come up with hacks to work around these
limitations.  But they always have been, and always will, be hacks and
recognize them for the ugliness that they are.  Better to dispense
with such hacks when ever possible.  We must strive to work within
these limits and treat any time that we work outside of those limits
as kludges and abject failures.

* 8 

Most of these kludges fall into two categories, chunking and mapping.
We can expand our working memory by grouping large groups of things
into chunks.  We can remember large numbers by breaking the numbers
into smaller groups that can be treated as a single item in memory.
Another is to use uniforms.  The reason that sports teams, police,
military and even schools use uniforms is so we can chunk together
people into teams that we can treat as single units.  The second
method, mapping, reduces large complex things to very simplified
general outlines of larger things.  This enables us to see the forest
for the trees, but it comes at an expense.  We are so used to using
maps to navigate the world around us that we have forgotten that they
are maps.  All incarnations of commerce, governance and daily life are
now almost entirely experienced through filters that reduce the
complexity of the world to simple models and maps.  Most people
believe that the map is the territory.  Ignoring the complexity of
something and only considering a simplification of it, more often than
not ends in failure.  And rather than putting down the map and
confronting complexity we simply try to develop a new map that doesn't
suck as much as they one before.  Every time we chunk and map people
we dehumanise them and cause suffering and misery.  We simplfy markets
and reduce everything to property that has a value and can be bought
and sold and get economic theories that don't work.  Instead of
understanding that you can't treat everything as a commodity being
bought and sold in a market, we throw away the theory and try to find
a new theory.  When governments undertake massive urban development
projects that reduce people to units that require X amount of square
meters of space, X amount of electricity and X amount of caloric
intake a day we are amazed when it fails.  Rather than treating human
communities as being a surprisingly complex entaglement of motives,
needs, relationships and needs, we toss the plan and develop a new
plan.  When we throw away the interconnected complexity of natural
ecosystems and replace them with single species monocultures we begin
a process that inevitably collapses after a long process trying to
solve each problem that comes along, from pests, to disease, to the
effects of the climate results in a destruction of the soil, poisoning
both land and water with insecticides, fertilizers and antibiotics.
In the end there is nothing to be done except abandon the land and
move on to repeat the process on new land, leaving behind barren,
lifeless waste that will take millennia to restore.

* 9 

So why do we keep doing this to ourselves?  Part of the reason is that
our cognitive limitations make it difficult and even close to
impossible to understand large complex systems.  We are terrible at
thinking in time scales that are longer than even small fractions of
our lifespans.  We can only see today, and perhaps a few months or
even a few years down the road.  If we really push it we might be able
to see the fuzzy image of our children or grandchildren but no
farther.  Our small working memory allows us to do unspeakibly stupid
and evil things to places and futures that are too far away for us to
comprehend and relate to.

* 10

As depressing as all of this is, and I can't stress enough how serious
the things we can not see are and how they can not be mapped or
chunked away.  History is littered with civilization after
civilization who waxes large and fat for a time, only to wane and
eventually collapse as resources are exhausted and hacks to get around
limitations no longer work.  The primary reason the present paradigm
is collapsing is that we have hit the limits of the hacks we have
developed to cope with complexity.  The old tricks no longer work and
we need to go back and build a new framework that can enable a new
generation of hacks.  But this time, we have the chance of not just
replacing one map for a new one, but to go back to first principles
and build something new that acknowledges and works with the
complexity rather than mapping away the complexity and hoping it will
go away.  If we can put our large general purpose cortex to good use
it can be done.  Further, I believe that man's technology is now
reaching a complexity threshold that it will be up to the challenge of
understanding the complexity of large systems for us.

* 11




* The Chenla Institute

A distributed (as MIT MediaLab puts it) anti-disciplinary
research institute incorporated in Singapore, Germany and
France ??? with it's first campus located at Prek Leap
National College of Agriculture in Cambodia.

The Institute's mandate is to develop, document and deploy
the descriptive and proscriptive information, code, designs,
and ideas needed to establish a highly distributed
civilization for Mankind.

The Institute will work with governments, NGOs and industry
to understand and adapt to the radical changes that will
reshape our civilization in the coming decades, and to spin
off commerical and non-profit organizations and companies
that will implement the technologies developed at the
Institute.

The Institute is commited to openess and transparency.  All
works will be released under open source/content/design
licences and made availble as widely as possible.

* Organization

 - organization & legal
    - Centre for Distributed Civilization
    - Chalkhall
    - Centre for Grass Studies
    - b>i Research Group
    - Chenla Scopic Press
    - D9D Services

** Centre for Distributed Civilization

The Centre for Distributed Civilization conducts research
and development for the core mandate of the Institute.  The
Centre's core work will be in developing /The Primer/ which
is a compendium of all knowledge required to build and
maintain a distributed technological planetary civilization.
The primer is far from being an archive or library in the
traditional sense.  It is both descriptive as well as
proscriptive in nature and designed to be a living document
that is not just referred to but put into practice and
maintained in living memory.

** Centre for Grass Studies

The Centre for Grass Studies is being established to focus
on the study and development of technologies, techniques,
and understanding of the crucial role of grasses in human
civilization.  Specifically, the Centre will focus on three
different areas.  Frist, Bamboo, it's production, processing
and uses.  And secondly, grass as a crop in the form of
cereals for human consumption.  And third, as forage which
is part of /agricultural savannahs/ that mimic natural
savannah ecosystems that reduce external inputs on land used
for cereal production, as well as the production of meat,
milk and eggs.

** b>i Reseach Group

The b>i research group, is a distributed research group
established to conduct planned research and development
projects that support work being done at the Institure.

b>i research projects will aim to have the dual goal of
providing pragmatic solutions that benifit people today,
while also helping to further long term research and
development goals that fulfill Chenla's mandate to build a
distributed civilization.

Initially, projects will be based out of facilities at the
PNCA campus at Prek Leap, but scientists, engineers and
programers will participate in projects remotely and through
sabbatical, fellowship and internship programs.

** Chenla Scopic Press

Chenla will run it's own unique academic publishing company
called a /scopic press/.

A scopic publication not only includes narrative works that
constitute a traditional book, but all of the surrounding
context of the book which are typically only linked to in
hypertext links (in electronic formats) as well as in
references, footnotes and bibliographies.

The full publication will be in electronic formats that
include all materials as well as an index which can be
imported into a graph database.  Users will then be able to
build personal libraries where works are woven together with
personal notes, correspondence, bookmarks, excerpts and
quotes, works in progress, glosses and other annotations.

Multiple editions will be published with different subsets
of the full scopic texts in both electronic and print that
will more closely resemble traditional books.

Chenla will publish original works, as well as /scopic
editions/ of select works which are deemed important to
realizing Chenla's mandate to build a distributed
civilization.

** Chalkhall
:PROPERTIES:
:ID:       301a4758-d591-4e82-9f7a-c17037c21f0a
:END:

Chalkhall is an ongoing program for rethinking education in
the 21st century.

What we know about the world is constantly changing. Facts
that you learned in school are out of date or just plain
wrong in a decade cite:arbesman:2012half-life

The technology you use today, is already out of date,
development has moved on before you have even heard about
it.

schools are now keeping up with either facts or technology
-- and they are not teaching students how to learn on their
own, or give them the cognitive tools they will need for a
career that is in constant change.

learning can not longer be a place you go, or a time in your
life where you learn what you need for the rest of the your
life.  learning needs to become a habit that you practice
every day, like exercise.

Technology is changing so rapidly that careers will change
dramatically over the course of a lifetime.



** D9D Services

D9D is shorthand for Distributed (9 characters between the
two d's).

D9D Services provide the IT and Networking infrastructure
for everything being done under the Chenla Institure
umbrella.

Services will be divided into four parts:

  - Compute   :: containerized cloud computing services
  - Store     :: digital storage (block, object & filesystem)
  - Cognition :: machine learning services
  - Graph     :: graph database as a service

All services will be provided through the IPFS network, so
that services may be distributed across different, servers,
clusters and cloud providers around the world.

Services will be provided to all Chenla projects.  They will
also be offered free of charge to the larger Chenla
community for hosting projects that are free and open
source, that work towards Chenla's mandate of building a
distributed civilization.  Services will also be provided to
NGOs, colleges & universities for reasearch or providing
online educational courseware that are open and free to the
public.

A commercial spinoff of D9D Services will be provided under
the name /Kinto Cloud Services/ which Chenla will maintain
shares in.

* Facilities

 - Viz Centre : collaboration and conference space
 - Fab Lab    : tool & machine fabrication
 - Map Lab    : content & code
 - Wet Lab    : Gene Splicing & Agricultural Biotech
 - DataCenter : Containerized Process Cluster

Renovation of existing structures @prekleap 
 - exisiting buildings
 - riverfront erosion control & development
 - modular containerized data center
 - solar & gasification electrical generation

Equipment List
 
 - servers and routers
 - converted 20 foot ISO shipping containers

 - CNC milling, router & plasma cutters
 - 3D Printing
 - Metal/Machine Shop
 - Wood Shop
 - Electrical/Electronics Shop     

 - CRSPR gene splicers
 - tissue culture lab
 - 

* People

  - people:
    - faculty 
    - sabbatical program
    - fellowship program
    - internship program
    - tutorial program

* Events & Publications

  - Conferences, Symposia, & Summits
  - Journal, Books -- original works and reprinting
    important works that are crucial to building and
    maintaining a distributed civilization.

* Financial

While we will actively seek our and apply for grants,
relying on grants for funding, or any one source of revenue
is not sustainable.

  - Corporate Sponsorship
  - Endowments
  - Consulting Services
  - In-Kind Donations

