#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Bluebook 
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/tldr/chenla-bluebook/bluebook.org
  :Created:   2017-06-07T15:35@Prek Leap (11.642600N-104.919210W)
  :ID:        a043e6f1-ec8a-4d60-af71-ad54ee012fed
  :VER:       550096596.118544686
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:GHT4-5465
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction
* The Chenla Institute

A distributed (as MIT MediaLab puts it) anti-disciplinary
research institute incorporated in Singapore, Germany and
France ??? with it's first campus located at Prek Leap
National College of Agriculture in Cambodia.

The Institute's mandate is to develop, document and deploy
the descriptive and proscriptive information, code, designs,
and ideas needed to establish a highly distributed
civilization for Mankind.

The Institute will work with governments, NGOs and industry
to understand and adapt to the radical changes that will
reshape our civilization in the coming decades, and to spin
off commerical and non-profit organizations and companies
that will implement the technologies developed at the
Institute.

The Institute is commited to openess and transparency.  All
works will be released under open source/content/design
licences and made availble as widely as possible.

* Organization

 - organization & legal
    - Administrative office
    - Centre for Distributed Civilization
    - Centre for Grass Studies
    - b>i Research Group
    - Chenla Scopic Press
    - D9D Services


** Centre for Distributed Civilization

** Centre for Grass Studies

** b>i Reseach Group

The b>i research group, is a distributed research group
established to conduct planned research and development
projects that support work being done at the Institure.

b>i research projects will aim to have the dual goal of
providing pragmatic solutions that benifit people today,
while also helping to further long term research and
development goals that fulfill Chenla's mandate to build a
distributed civilization.

Initially, projects will be based out of facilities at the
PNCA campus at Prek Leap, but scientists, engineers and
programers will participate in projects remotely and through
sabbatical, fellowship and internship programs.

** Chenla Scopic Press

Chenla will run it's own unique academic publishing company
called a /scopic press/.

A scopic publication not only includes narrative works that
constitute a traditional book, but all of the surrounding
context of the book which are typically only linked to in
hypertext links (in electronic formats) as well as in
references, footnotes and bibliographies.

The full publication will be in electronic formats that
include all materials as well as an index which can be
imported into a graph database.  Users will then be able to
build personal libraries where works are woven together with
personal notes, correspondence, bookmarks, excerpts and
quotes, works in progress, glosses and other annotations.

Multiple editions will be published with different subsets
of the full scopic texts in both electronic and print that
will more closely resemble traditional books.

Chenla will publish original works, as well as /scopic
editions/ of select works which are deemed important to
realizing Chenla's mandate to build a distributed
civilization.

** D9D Services

D9D is shorthand for Distributed (9 characters between the
two d's).

D9D Services provide the IT and Networking infrastructure
for everything being done under the Chenla Institure
umbrella.

Services will be divided into four parts:

  - Compute   :: containerized cloud computing services
  - Store     :: digital storage (block, object & filesystem)
  - Cognition :: machine learning services
  - Graph     :: graph database as a service

All services will be provided through the IPFS network, so
that services may be distributed across different, servers,
clusters and cloud providers around the world.

Services will be provided to all Chenla projects.  They will
also be offered free of charge to the larger Chenla
community for hosting projects that are free and open
source, that work towards Chenla's mandate of building a
distributed civilization.  Services will also be provided to
NGOs, colleges & universities for reasearch or providing
online educational courseware that are open and free to the
public.

A commercial spinoff of D9D Services will be provided under
the name /Kinto Cloud Services/ which Chenla will maintain
shares in.

* Facilities

- Viz Centre : collaboration and conference space
- Fab Lab    : tool & machine fabrication
- Map Lab    : content & code
- Wet Lab    : Gene Splicing & Agricultural Biotech
- DataCenter : Containerized Process Cluster

Renovation of existing structures @prekleap 
 - exisiting buildings
 - riverfront erosion control & development
 - modular containerized data center
 - solar & gasification electrical generation

Equipment List
 
 - servers and routers
 - converted 20 foot ISO shipping containers

 - CNC milling, router & plasma cutters
 - 3D Printing
 - Metal/Machine Shop
 - Wood Shop
 - Electrical/Electronics Shop     

 - CRSPR gene splicers
 - tissue culture lab
 - 

* People

  - people:
    - faculty 
    - sabbatical program
    - fellowship program
    - internship program
    - tutorial program

* Events & Publications

  - Conferences, Symposia, & Summits
  - Journal, Books -- original works and reprinting
    important works that are crucial to building and
    maintaining a distributed civilization.

* Financial

While we will actively seek our and apply for grants,
relying on grants for funding, or any one source of revenue
is not sustainable.

  - Corporate Sponsorship
  - Endowments
  - Consulting Services
  - In-Kind Donations

