#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Bluebook
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/tldr/chenla-bluebook/bluebook.org
  :Created:   2017-06-07T15:35@Prek Leap (11.642600N-104.919210W)
  :ID:        a043e6f1-ec8a-4d60-af71-ad54ee012fed
  :VER:       550096596.118544686
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:QIC6-1753
  :Class:     deploy
  :Type:      tldr
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-tl;dr-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

[[./index.org]]


* First Admonition

What you are holding in your hand distills what we are doing
as far as it can be distilled without loosing so much
context that it becomes meaningless.  Anyone who thinks that
large complex things can be boiled down to a dark greaser
smear in a couple of paragraphs, a table and a couple of
charts is delusional.  The greasy smear approach, which is
commonly called an /elevator pitch/ might be appropriate to
explain an iteration on an existing idea.  But fails totally
when describing a non-incremental innovation.  This is not a
pitch, it's an overview of foundational work that we are
building a number of commercial and not-for-profit projects
on.

* 1


In the structure of scientific revolutions, Kuhn describes
science as being a progression of different paradigms.  A
paradign is a nebulous assemblage of recorded observations,
theories, best practices and information that share a common
vocabulary and structure that science is done in.  Over
time, new observations that don't fit the paradigm begin to
build up until the paradigm is broken and everyone scrambles
to come to a consensus around a new paradigm that better
explains the evidence.  This is a useful way of
understanding a very wide range of human activity from
government, to business, education and the arts.

* 2

Our civilization is at the very end of a paradigm that has
been in place since the end of the World War II.  But the
number of anomolies have now piled up to the point where we
are now reaching a critical threshold just before the
paradigm shatters and needs to be replaced.  That period of
scrambling around trying to find a new consensus is not only
messy but a potentially dangerous time to be alive.  Very
bad things happen, because most people will spend all of
their energy trying to salvage the paradigm rather than let
it go and move on.  Climate-change denial, extreme
nationalistim, poplulism and straight-out fascism is
suddenly attractive to a large number of people who are
threatened as the decaying paradigm collapses.  At the same
time, such times are exciting to live through, whole new
worlds become possible that would have been dismissed as
impractical or even impossible a few years before.  We live
in interesting times, and for many that is a bad thing.  But
for some, it is liberating and exhilerating.  This is the
time to identity and place bets on those people, not the
timorous Luddites cowering in the shadows praying for a
return of a golden past that never existed.

* 4

Now is the time to go back to first principles and
understand who we are, how we got to where we are and where
things are headed in order to understand how things need the
change and what needs to be be built that will eventually
become part of the new consensus.  This is exactly what we
have been working on for twenty years.  We don't need to
play catch-up because we started work on this back when the
cracks were getting large enough in the dike to realise the
inevitibility of the dike's collapse.  It's only been in the
past 18 months that it is now clear that the collapse is now
imminent and through the cracks which have widened to become
gaping rents to see the shape of what lies beyond.  As yet
these are still shapes.  We know that what is now inevitable
but we still don't know the final form they will take.
We're just starting to look for solutions that we can all
agree on.

* 5

All species, plant, insect, animal or microbial evolve to
fill a specific niche in an ecosystem, full stop, no
exceptions.  Keep in mind that an ecosystem is a system.
Systems are made up of different parts that must work
together for the system to keep running.  Again, no
exceptions.  Homo Sapiens is a species of hominid that
evolved to fill a niche in the African savannah ecosystem.
When we spread beyond the savannah and eventually over the
entire planet, we had to take enough of the savannah with us
to survive.  Things like clothes, cooked food, and shelter
all helped us to adapt to climates we were not designed to
live in.  That ability to dynamically adapt in real time is
what sets us apart from other species.  We are not bound by
the hardcoded instincts that comes with a limbic system.
Our freakishly large cerebral cortex can be thought of as a
general purpose programable computer.

* 6

Civilization emerged from the agricultural revolution as
settlements grew larger in size and complexity than nomadic
social structures could maintain.  Humans did not evolve to
live in herds.  We are pack animals, fleet of foot and able
to think on our feet.  Packing each other into close
quarters with no chance to escape each other is not the
niche we evolved to fill.

If pressed, I would say that if you had to pick a single
thing that goes to the root of all of mankind's problems,
that would have to be the problem of scale.  Everything that
Man has done that is good, as well as everything we have
done that is bad can be understood as a scaling problem.

* 7

Humans have a very small amount of working memory.  We can
only keep at the most, three things on working memory at a
time.  Our short term memory is slightly larger which is
expressed as the magic number seven plus or minus two.
Recent research indicates that the number is closer to for
or five.  We can only maintain relationships with a maximum
of 150 people, what is known as Dunbar's number.  This means
we are able to related to people less and less as a group,
communitiy or organizations increases in size.  We can only
maintain close relationships with a handful of people,
topping out at fourteen or less.  These are the numbers that
we must stay within when we design buildings, businesses and
governments.  The story of civilization is the story of how
we come up with hacks to work around these limitations.  But
they always have been, and always will, be hacks and
recognize them for the ugliness that they are.  Better to
dispense with such hacks when ever possible.  We must strive
to work within these limits and treat any time that we work
outside of those limits as kludges and abject failures.

* 8 

Most of these kludges fall into two categories, chunking and
mapping.  We can expand our working memory by grouping large
groups of things into chunks.  We can remember large numbers
by breaking the numbers into smaller groups that can be
treated as a single item in memory.  Another is to use
uniforms.  The reason that sports teams, police, military
and even schools use uniforms is so we can chunk together
people into teams that we can treat as single units.  The
second method, mapping, reduces large complex things to very
simplified general outlines of larger things.  This enables
us to see the forest for the trees, but it comes at an
expense.  We are so used to using maps to navigate the world
around us that we have forgotten that they are maps.  All
incarnations of commerce, governance and daily life are now
almost entirely experienced through filters that reduce the
complexity of the world to simple models and maps.  Most
people believe that the map is the territory.  Ignoring the
complexity of something and only considering a
simplification of it, more often than not ends in failure.
And rather than putting down the map and confronting
complexity we simply try to develop a new map that doesn't
suck as much as they one before.  Every time we chunk and
map people we dehumanise them and cause suffering and
misery.  We simplfy markets and reduce everything to
property that has a value and can be bought and sold and get
economic theories that don't work.  Instead of understanding
that you can't treat everything as a commodity being bought
and sold in a market, we throw away the theory and try to
find a new theory.  When governments undertake massive urban
development projects that reduce people to units that
require X amount of square meters of space, X amount of
electricity and X amount of caloric intake a day we are
amazed when it fails.  Rather than treating human
communities as being a surprisingly complex entaglement of
motives, needs, relationships and needs, we toss the plan
and develop a new plan.  When we throw away the
interconnected complexity of natural ecosystems and replace
them with single species monocultures we begin a process
that inevitably collapses after a long process trying to
solve each problem that comes along, from pests, to disease,
to the effects of the climate results in a destruction of
the soil, poisoning both land and water with insecticides,
fertilizers and antibiotics.  In the end there is nothing to
be done except abandon the land and move on to repeat the
process on new land, leaving behind barren, lifeless waste
that will take millennia to restore.

* 9 

So why do we keep doing this to ourselves?  Part of the
reason is that our cognitive limitations make it difficult
and even close to impossible to understand large complex
systems.  We are terrible at thinking in time scales that
are longer than even small fractions of our lifespans.  We
can only see today, and perhaps a few months or even a few
years down the road.  If we really push it we might be able
to see the fuzzy image of our children or grandchildren but
no farther.  Our small working memory allows us to do
unspeakibly stupid and evil things to places and futures
that are too far away for us to comprehend and relate to.

* 10

As depressing as all of this is, and I can't stress enough
how serious the things we can not see are and how they can
not be mapped or chunked away.  History is littered with
civilization after civilization who waxes large and fat for
a time, only to wane and eventually collapse as resources
are exhausted and hacks to get around limitations no longer
work.  The primary reason the present paradigm is collapsing
is that we have hit the limits of the hacks we have
developed to cope with complexity.  The old tricks no longer
work and we need to go back and build a new framework that
can enable a new generation of hacks.  But this time, we
have the chance of not just replacing one map for a new one,
but to go back to first principles and build something new
that acknowledges and works with the complexity rather than
mapping away the complexity and hoping it will go away.  If
we can put our large general purpose cortex to good use it
can be done.  Further, I believe that man's technology is
now reaching a complexity threshold that it will be up to
the challenge of understanding the complexity of large
systems for us.

* 11

This is not wishful thinking.  There is good reason to
believe that we now possess, or will soon have to capacity
and capiblity to solve most of the important problems that
man and the ecosystems we inhabit will face this century.
But to understand this we need to understand that man's big
brain crossed a cognitive threshold that allowed us to think
outside of ourselves in a very limited but important way.
We have the ability, that is only shared by a handful of
other old world primates, to comprehend the intention of
others.  We can point at a hill and other humans understand
that we are communicating an intent that is connected to
that hill.  A Golden Retriever just sees you pointing a
finger.  This unique, almost magical ability makes it
possible for humans to extend, externalize, and specialize
mind, memory and muscle.  First came crude tool building and
mastering fite.  Next came spoken language which made it
possible to communicate and cooperate with each other by
extending our thoughts and intents with others.  Written
language externalized speech and made it possible to
communicate with those far away in space in time who you
will never meet or know about.  Hand tools, are an extension
of the hand.  Complex machines, externalized tools and made
it possible to literally hand-off work to a device that can
work independently of of our physical bodies.  Communication
networks which started as networks for transporting physical
messages turned into radio and telegraph networks allowing
us to communicate in real time anywhere on the planet.
Finally, mind was replicated in programable machines that
can think.  We're not talking about human level cognition,
but computational devices do think, allowing us to
externalize cognitive processes.  Most recently we are now
combining externalized muscle in the form of mechanical
machines, and externalized mind in the form of computers
together to create robotics.  Machine cognition is now
beginning to become capable enough to do tasks that only
humans could perform before.  We call this artificial
intelligence.  Taken together, AI and robotics will soon be
able to replace the vast majority of industrial and
information work that makes up an industrial civilization.
The industrial revolution was founded on using humans as
machines -- put simply, slavery.  Human as machines made
civilization and all of it's innovations and advances
possible at the cost of dehumanizing most of our fellow man
and treating them as little more then clever mechanical
devices.

* 12

Putting this all together, we can put to an end to human
slavery and it's modern incarnation, the industrial salary
worker who is only free in name only.  For all practical
purposes industrial workers were not economically free to
leave their jobs accept to exchange one industrial job for
another.  Industrial work meant large swaths of the
population having to live close to large industrial centers
at a low standard of living and education with little to no
chance of it getting better.  Automation in the form of AI
operating machines will make this possible.

* 13

Machine cognition is, by definition, not human and need not
have the same cognitive and memory restrictions that humans
have.  This will make it possible for us to build cognitive
machines who can understand complexity that is beyond our
limitations and to think and work in time scales that are
far faster than we can, as well as far longer and slower
that we are capable of.  As Kevin Kelly explained, there
will not be just one kind of AI and we must stop trying to
project ourselves and our limitations into cognitive
machines.  Anthropomorphism is both stupid and potentially
dangerous.  Making machines a reflection of ourselves is a
bad idea and there is no reason to build things which share
all out shortcomings while also giving them capabilities
that exceed our own.  We are still very far from being able
to build such machines and I believe that over time, as we
begin to understand what AI is and how it works, that what
we are building is not a reflection of ourselves, but an
extension and externalization of ourselves that can operate
at scales of time, space and complexity on our behalf that
are impossible today.  Again, this is not wishful thinking,
once we understand that all tools be they a hammer, or a CNC
milling machine or a supercomputer that can beat the world's
Go masters are us.  We are simply extending and
externalizing ourselves.  And we must find the wisdom that
we are capable of, to wisely extend and externalize
ourselves in ways that help make the world a better place
rather than to destroy each other.

* 

The impact that the combination of ubiquitous and AI and
Robots will be as large or larger than the Industrial
Revolution.  The biggest change will be to restructure what
is called today the global-value chain.  The industrial
revolution was all about centralization and concentration of
production into a relatively small number of places in
Europe, North America and Japan.  There was a corresponding
industrialized transformation of agriculture with the
majority of small farms being replaced by a relatively small
number of massive farms which specialized in two or three
different crops at most.  Industrialization was all about
scale.  In each case, the only way to scale was through
simplification and standardization of processes and
toolchains.  Skilled artisans were replaced by semi-skilled
workers who each performed single tasks repeatedly. The
master craftsman who could produce things of high quality
that were custom made to meet the needs of the customer were
replaced by mass production of identical copies of things at
lower quality.  The difference between the two was cost.  A
master could only produce a small number of items slowly and
at high cost.  A factory could produce a large number of
items far cheaper but at the cost of providing workers with
meaningful varied work and quality of goods.

There is a adage that you can have something, fast, cheap or
good, but you can only have two.  Industrialization made
things cheap and fast at the cost of good, replacing a
system what was good at the cost of either being fast or
cheap. There is no question that industrialization helped to
raise the standard of living for most of the world.

The same applies to farming.  It's always been true that
small farms are far more productive than large farms.  Large
farms are specialists that produce one or two things at
large scale.  Small farms are generalists who produce a
large number of things in small quantities.  The increase in
productivity of small farms was only possible through
brutally high labor intensive practices.  The second problem
for small farms is that they didn't have access to logistics
networks that could get their produce quickly to large urban
centers where they could command higher prices.  Like their
factory counterparts, large farms produced lower quality
food in large quantities cheaply.  The higher quality and
variety of food that smaller farms produced couldn't
compete.  Fast and cheap nearly always beat slow or
expensive and good.

* 

The industrial miracle came with a number of hidden costs.
Natural resources were treated as essentially being free and
limitless.  There was little to no effort to use resources
sustainably and short term goals of making as much money
meant that resources, some of which required decades,
centuries or in the case of fossil fuels, tens of millions
of years to replace.  Before industrialized farming, the
great plains in the American mid-west had rich topsoil that
sometimes was several meters in depth.  In many places this
top soil which took centuries to build up by a diverse
ecosystem that required a wide range of animals from
megafuana such as the Mamouth, elk and deer, to burrowing
mammals, a wide variety of birds and incests.  All of that
complexity was replaced by monoculture farming that treated
all of of that diversity as pests.  What took centuries
after the Ice Age to build up has taken less than fifty
years to all but exhaust it.


* 

The second stage of the industrial revolution began in the
1980's as inexpensive data processing, global voice and data
networks transformed business and banking making it possible
for information and money to flow across international
borders as easily as within a country.  At the same time,
transportation of goods standardized around modal shipping
containers, the now ubiqutious standard ISO 40' shipping
container.  This made it possible for factory owners to move
production to factories to a handful of countries who had
missed out on the first industrial wave, where labor was
still inexpensive.  The 40 foot container became the defacto
atomic unit of Globalization.  It transformed the global
economy in the same way that the handful of countries had
been transformed in the first wave of industrialization.
This came at a cost.  Centralization of production drove
countless small companies out of business.  No company could
compete who could not produce goods in units that filled 40
foot shipping containers and could be transported easily to
a container port for export.

* 

Centralization and simplication was not just a feature of
the industrial revolution it was a precondition that made
scaling possible both for production and many aspects of
governance of nation-states who were struggling to manage a
population explosion after the end of the World War II that
increased the world population from xxx to xxx in xx years.

In the past 50 years the nation-state has lost control over
many things that used to be under control of the state.  The
flow of money and information is now effectively
borderless.  Which makes it increasingly difficult for
countries to keep wealth within borders and to effectively
tax goods and services that now might be located almost
anywhere on the planet.  This threatens not only the power
of the state, but severely impacts the ability of states to
collect tax revenue.  States now concentrate on one of the
few things that they still can control, which is the flow of
people across their borders, and increasingly, monitoring
and controlling the activities of people within their borders.

* 

It's becoming increasingly clear that the process of
centralization and simplication is reaching practical
limits and that another mechanism is about to kick in.

Technology is at inherently disruptive.  Major technological
innovations arise to meet needs that existing technologies
can no longer meet, this results in existing power
structures being broken up and the power moves to the edges
where the new technology has the most impact. In the
beginning the benifits are seen by many and the barrier for
adopting the technology and using it is low enough for
almost anyone to use it.  As the technology matures it also
is pushed to its limits and improvements become increasingly
expensive to realize increasingly smaller improvements.
This naturally favors large organizations with deep pockets
who use their wealth to buy out or push out all smaller
players, resulting in monoplolies or duopolies.  The
world wide web is a classic example.  The internet and the
web is designed to be decentralized.  However, when it was
invented no one had any idea that it would quickly scale
globally.  As the web grew, a crucial flaw in the original
design became clear.  The decentralized nature of the system
made resource discovery difficult.  Finding things simply
didn't scale.  So it was natural that search engines became
centralized services that provided a means for the web to
scale.  This set the stage for everything that followēd,
including the rise of the big five companies.  Small
companies can not compete with these companies and are
bought or pushed out of business.

The same factors that made Amazon, Google, Facebook, Baidu
and Alibabba possible will also work against them.  IBM once
dominated computing when it was based on mainframe computers
that required entire floors of buildings.  Eventually, mini
computers from companies like DEC (digital equipment
company), and Wang broke up the centralized mainframes and
moved computational power to middle sized companies.  Mini
computers which could fit inside several boxes the size of
refridgerators dominated until smaller servers that could be
fit in cases the size and shape of a pizza box from
companies like Sun began to threaten mini computers.
Shortly after, the PC revolution arrived turning small
expensive pizza boxes into commodity hardware that anyone
could afford.  Power again moved to the edge until the
technology matured and required centralized and expensive
solutions to make ever smaller incremental improvements.

* 

The cycle is set to repeat again and soon.  Not all
iterations of this cycle are created equal.  The
Agricultural and Industrial revolutions are deserving of the
name revolution because they transformed every aspect of
human society, from where and how we live, to the structure
of families, how we organize states, communicate and
cooperate.  The computer and telecommunications revolutions
have changed the world, but they haven't yet reshaped the
concept of family in the way that the agricultural
revolution replaced nomadic bands with sedantary family
units that we now call extended families.  The industrial
revolution broke up extended families and replaced them with
the modern concept of the nuclear family.  The agricultural
revolution led to the invention of the State.  The
industrial revolution led to the dominance of the
nation-state.  The coming decades will see changes to human
life equal to or greater than what has happened before.  A
century from now we will look back and see that the Internet
and Web was just the first step of a far deeper revolution
that will reshape humanity and our planet.  At present it's
no clear that this revolution is now inevitable, but we
still don't know specifically what form it will take.  Now
that we have established context for where we are and where
we are headed we can begin to explore what is possible, and
even desireable.  It is up to us to make it happen.

* 

Let's start with broad strokes.  The revolution we are now
in will lead to systematic decentralization.  As we have
seen throughout history, this is a no-brainer.  The thing
that will set this revolution apart is that it will
transform the very things that always resulted in the
pendulum swinging back towards centralization.  We have
discussed how small shops could produce superior goods, but
they were slow and expensive.  In the same way, small farms
were far more productive, but required enormous amounts of
labor intensive work to do so.  We have also seen how
mankind has relentlessly extended and externalized mind,
memory and muscle and that robotics which is the marriage of
AI and machines is, in many ways a culmination of this
process that began with the development of the first spoken
languages.  

This will result in something that will be surprising to
most people.  The most important change that will result
from a decentralized world based on AI and automation will
be that small scale production will become as efficient as
large scale production is today.  AI will make it possible
for small systems that can manage high levels of complexity
to out perform large systems that need simplication and
centralization to work at scale.  AI will transform
logistics so that small production can be coordinated and
aggregated in far more flexible and efficient configurations
than large centralized systems can do today.  Put simply,
the entire world order will be flipped so that small and
distributed will beat big and centralized.  This is not
limited to production of goods and services, but will
cascade through every aspect of human life and society.  It
will transform our present concept of the State into
something that would not be recognizable today.  It will
change the nature of work from being mostly a means to an
end for survival and decouple work from from survival to
that it becomes something we do because it gives us meaning
and purpose.  This has to happen because automation will
replace the vast majority of work that now requires people
to do dull, dangerous and mindless tasks.  The machines will
take over all the crappy jobs and we work will need to
provide things that machines are not good at.

Putting this all together, it's possible that this iteration
of technological disruption is fundamentally different from
all the others.  This is not an iterative progression, we
are crossing a complexity threshold that will result in a
systematic transformation that brings together a wide range
of advances that result in a fundamental transformation not
only human culture and society but potentially could result
in a a qualitative leap in human well being.  If that sounds
crazy it should, because it's still far from clear what form
this revolution will take. Now that we have an idea of the
big picture we can begin to work out how to shape that
future to be a world we want to live in.

* 

Let's start with specifics and outline an aspirational
senario for the average person fifty years from now in a
decentralized post-scarcity civilization dominated by AI and
robotics.  If that sounds like a plot for a science fiction
story, that is okay. If you went back forty years in time
and described a world where self-driving cars are being
tested in cities aound the world.  Where everyone has a
computer in their pocket that costs a couple hundred dollars
and is more powerful than the world's fastest super computer
it would sound as just as absurbly science fiction as the
world will be fifty years from now.  As William Gibson
famously said, the future is already here, it's just not
evenly distributed.  The future we are outlining will be
increasingly common in fifty years in developed economies.
It might take another fifty years or more for the rest of
humanity to catch up.

  1. Universal Basic Income, Housing & Medical Care
  2. Lifelong Learning
  3. Remote Work for knowledge workers
  4. Small local shops and farm-based production
  5. Federated local infrastructure & governance
  
Reading that I imagine you are either shrugging your
shoulders thinking that this isn't very science fictiony, or
thinking that this is an absurd utopian dream.  It's
neither.  There are no simple fixes for many social
problems, no matter how good we have it, Man is still tends
to be a self-serving lot.  We are gullible, short-sighted,
prone to violence, self-destructive behavior and as a
general rule have terrible taste in music.

That said, there is a monumental amount of empirical
evidence that shows that if you can materially improve the
physical and social well-being of people, things get better.
We live longer, healthier and more secure lives.  Wars
become the exception rather than the rule, violent death
becomes rare, the birth rate  goes down because women no
longer die in child birth and those children don't die
before their tenth birthday. We are less likely to die in
industrial accidents or while going to work.  All of this
is what has already happened over the past fifty years.
It's not utopian to expect that these trends can continue
over the next fifty years.

Structurally these five items are not possible in the
present system.  Life and work in industrial societies
revolves around the workplace as being separate from home
and family life, children are sequestered in schools and
other activities while parents are at work and take no part
in adult life.  Survival is contingent on getting a job, and
your level of existence is determined by where you happen to
be on a social and economic hierarchy.  Education is little
more than preparation for a lifetime in a workplace that
rewards people who stay in one place for long periods of
time and do what they are instructed without question.  The
workplace and societies we belong to are, more often than
not, far larger than human scale and are impersonal, often
demeaning and dehumanizing.  We live in societies that
extoll the virtue and rights of freedom and self
determination, but in practise we have none of those things.







* ===============================

* The Chenla Institute

A distributed (as MIT MediaLab puts it) anti-disciplinary
research institute incorporated in Singapore, Germany and
France ??? with it's first campus located at Prek Leap
National College of Agriculture in Cambodia.

The Institute's mandate is to develop, document and deploy
the descriptive and proscriptive information, code, designs,
and ideas needed to establish a highly distributed
civilization for Mankind.

The Institute will work with governments, NGOs and industry
to understand and adapt to the radical changes that will
reshape our civilization in the coming decades, and to spin
off commerical and non-profit organizations and companies
that will implement the technologies developed at the
Institute.

The Institute is commited to openess and transparency.  All
works will be released under open source/content/design
licences and made availble as widely as possible.

* Organization

 - organization & legal
    - Centre for Distributed Civilization
    - Chalkhall
    - Centre for Grass Studies
    - b>i Research Group
    - Chenla Scopic Press
    - D9D Services

** Centre for Distributed Civilization

The Centre for Distributed Civilization conducts research
and development for the core mandate of the Institute.  The
Centre's core work will be in developing /The Primer/ which
is a compendium of all knowledge required to build and
maintain a distributed technological planetary civilization.
The primer is far from being an archive or library in the
traditional sense.  It is both descriptive as well as
proscriptive in nature and designed to be a living document
that is not just referred to but put into practice and
maintained in living memory.

** Centre for Grass Studies

The Centre for Grass Studies is being established to focus
on the study and development of technologies, techniques,
and understanding of the crucial role of grasses in human
civilization.  Specifically, the Centre will focus on three
different areas.  Frist, Bamboo, it's production, processing
and uses.  And secondly, grass as a crop in the form of
cereals for human consumption.  And third, as forage which
is part of /agricultural savannahs/ that mimic natural
savannah ecosystems that reduce external inputs on land used
for cereal production, as well as the production of meat,
milk and eggs.

** b>i Reseach Group

The b>i research group, is a distributed research group
established to conduct planned research and development
projects that support work being done at the Institure.

b>i research projects will aim to have the dual goal of
providing pragmatic solutions that benifit people today,
while also helping to further long term research and
development goals that fulfill Chenla's mandate to build a
distributed civilization.

Initially, projects will be based out of facilities at the
PNCA campus at Prek Leap, but scientists, engineers and
programers will participate in projects remotely and through
sabbatical, fellowship and internship programs.

** Chenla Scopic Press

Chenla will run it's own unique academic publishing company
called a /scopic press/.

A scopic publication not only includes narrative works that
constitute a traditional book, but all of the surrounding
context of the book which are typically only linked to in
hypertext links (in electronic formats) as well as in
references, footnotes and bibliographies.

The full publication will be in electronic formats that
include all materials as well as an index which can be
imported into a graph database.  Users will then be able to
build personal libraries where works are woven together with
personal notes, correspondence, bookmarks, excerpts and
quotes, works in progress, glosses and other annotations.

Multiple editions will be published with different subsets
of the full scopic texts in both electronic and print that
will more closely resemble traditional books.

Chenla will publish original works, as well as /scopic
editions/ of select works which are deemed important to
realizing Chenla's mandate to build a distributed
civilization.

** Chalkhall
:PROPERTIES:
:ID:       301a4758-d591-4e82-9f7a-c17037c21f0a
:END:

Chalkhall is an ongoing program for rethinking education in
the 21st century.

What we know about the world is constantly changing. Facts
that you learned in school are out of date or just plain
wrong in a decade cite:arbesman:2012half-life

The technology you use today, is already out of date,
development has moved on before you have even heard about
it.

schools are now keeping up with either facts or technology
-- and they are not teaching students how to learn on their
own, or give them the cognitive tools they will need for a
career that is in constant change.

learning can not longer be a place you go, or a time in your
life where you learn what you need for the rest of the your
life.  learning needs to become a habit that you practice
every day, like exercise.

Technology is changing so rapidly that careers will change
dramatically over the course of a lifetime.



** D9D Services

D9D is shorthand for Distributed (9 characters between the
two d's).

D9D Services provide the IT and Networking infrastructure
for everything being done under the Chenla Institure
umbrella.

Services will be divided into four parts:

  - Compute   :: containerized cloud computing services
  - Store     :: digital storage (block, object & filesystem)
  - Cognition :: machine learning services
  - Graph     :: graph database as a service

All services will be provided through the IPFS network, so
that services may be distributed across different, servers,
clusters and cloud providers around the world.

Services will be provided to all Chenla projects.  They will
also be offered free of charge to the larger Chenla
community for hosting projects that are free and open
source, that work towards Chenla's mandate of building a
distributed civilization.  Services will also be provided to
NGOs, colleges & universities for reasearch or providing
online educational courseware that are open and free to the
public.

A commercial spinoff of D9D Services will be provided under
the name /Kinto Cloud Services/ which Chenla will maintain
shares in.

* Facilities

 - Viz Centre : collaboration and conference space
 - Fab Lab    : tool & machine fabrication
 - Map Lab    : content & code
 - Wet Lab    : Gene Splicing & Agricultural Biotech
 - DataCenter : Containerized Process Cluster

Renovation of existing structures @prekleap 
 - exisiting buildings
 - riverfront erosion control & development
 - modular containerized data center
 - solar & gasification electrical generation

Equipment List
 
 - servers and routers
 - converted 20 foot ISO shipping containers

 - CNC milling, router & plasma cutters
 - 3D Printing
 - Metal/Machine Shop
 - Wood Shop
 - Electrical/Electronics Shop     

 - CRSPR gene splicers
 - tissue culture lab
 - 

* People

  - people:
    - faculty 
    - sabbatical program
    - fellowship program
    - internship program
    - tutorial program

* Events & Publications

  - Conferences, Symposia, & Summits
  - Journal, Books -- original works and reprinting
    important works that are crucial to building and
    maintaining a distributed civilization.

* Financial

While we will actively seek our and apply for grants,
relying on grants for funding, or any one source of revenue
is not sustainable.

  - Corporate Sponsorship
  - Endowments
  - Consulting Services
  - In-Kind Donations

