#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Bluebook
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/tldr/chenla-bluebook/bluebook.org
  :Created:   2017-06-07T15:35@Prek Leap (11.642600N-104.919210W)
  :ID:        a043e6f1-ec8a-4d60-af71-ad54ee012fed
  :VER:       550096596.118544686
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:QIC6-1753
  :Class:     deploy
  :Type:      tldr
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-tl;dr-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib


* First Admonition

What you are holding in your hand distills what we are doing as far as
it can be distilled without loosing so much context that it becomes
meaningless.  Anyone who thinks that large complex things can be
boiled down to a dark greaser smear in a couple of paragraphs, a table
and a couple of charts is delusional.  The greasy smear approach,
which is commonly called an /elevator pitch/ might be appropriate to
explain an iteration on an existing idea.  But fails totally when
describing a non-incremental innovation.  This is not a pitch, it's an
overview of foundational work that we are building a number of
commercial and not-for-profit projects on.

* 1

In the structure of scientific revolutions, Kuhn describes science as
being a progression of different paradigms.  A paradign is a nebulous
assemblage of recorded observations, theories, best practices and
information that share a common vocabulary and structure that science
is done in.  Over time, new observations that break the paradigm begin
to build up until the paradigm is broken and everyone scrambles to
come to a consensus around a new paradigm that better explains the
evidence.  This is a useful way of understanding a very wide range of
human activity from government, to business, education and the arts.

* 2

In the structure of scientific revolutions, Kuhn describes science as
being a progression of different paradigms.  A paradign is a nebulous
assemblage of recorded observations, theories, best practices and
information that share a common vocabulary and structure that science
is done in.  Over time, new observations that break the paradigm begin
to build up until the paradigm is broken and everyone scrambles to
come to a consensus around a new paradigm that better explains the
evidence.  This is a useful way of understanding a very wide range of
human activity from government, to business, education and
the arts.

* 3

Our civilization is at the very end of a paradigm that has been in
place since the end of the World War II.  But the number of anomolies
have now piled up to the point where we are now reaching a critical
threshold just before the paradigm shatters and needs to be replaced.
That period of scrambling around trying to find a new consensus is not
only messy but a potentially dangerous time to be alive.  Very bad
things happen, because most people will spend all of their energy
trying to salvage the paradigm rather than let it go and move on.
Climate-change denial, extreme nationalistim, poplulism and
straight-out fascism is suddenly attractive to a large number of
people who are threatened as the decaying paradigm collapses.  At the
same time, such times are exciting to live through, whole new worlds
become possible that would have been dismissed as impractical or even
impossible a few years before.  We live in interesting times, and for
many that is a bad thing.  But for some, it is liberating and
exhilerating.  This is the time to identity and place bets on those
people, not the timorous Luddites cowering in the shadows praying for
a return of a golden past that never existed.

* 4





* The Chenla Institute

A distributed (as MIT MediaLab puts it) anti-disciplinary
research institute incorporated in Singapore, Germany and
France ??? with it's first campus located at Prek Leap
National College of Agriculture in Cambodia.

The Institute's mandate is to develop, document and deploy
the descriptive and proscriptive information, code, designs,
and ideas needed to establish a highly distributed
civilization for Mankind.

The Institute will work with governments, NGOs and industry
to understand and adapt to the radical changes that will
reshape our civilization in the coming decades, and to spin
off commerical and non-profit organizations and companies
that will implement the technologies developed at the
Institute.

The Institute is commited to openess and transparency.  All
works will be released under open source/content/design
licences and made availble as widely as possible.

* Organization

 - organization & legal
    - Centre for Distributed Civilization
    - Chalkhall
    - Centre for Grass Studies
    - b>i Research Group
    - Chenla Scopic Press
    - D9D Services

** Centre for Distributed Civilization

The Centre for Distributed Civilization conducts research
and development for the core mandate of the Institute.  The
Centre's core work will be in developing /The Primer/ which
is a compendium of all knowledge required to build and
maintain a distributed technological planetary civilization.
The primer is far from being an archive or library in the
traditional sense.  It is both descriptive as well as
proscriptive in nature and designed to be a living document
that is not just referred to but put into practice and
maintained in living memory.

** Centre for Grass Studies

The Centre for Grass Studies is being established to focus
on the study and development of technologies, techniques,
and understanding of the crucial role of grasses in human
civilization.  Specifically, the Centre will focus on three
different areas.  Frist, Bamboo, it's production, processing
and uses.  And secondly, grass as a crop in the form of
cereals for human consumption.  And third, as forage which
is part of /agricultural savannahs/ that mimic natural
savannah ecosystems that reduce external inputs on land used
for cereal production, as well as the production of meat,
milk and eggs.

** b>i Reseach Group

The b>i research group, is a distributed research group
established to conduct planned research and development
projects that support work being done at the Institure.

b>i research projects will aim to have the dual goal of
providing pragmatic solutions that benifit people today,
while also helping to further long term research and
development goals that fulfill Chenla's mandate to build a
distributed civilization.

Initially, projects will be based out of facilities at the
PNCA campus at Prek Leap, but scientists, engineers and
programers will participate in projects remotely and through
sabbatical, fellowship and internship programs.

** Chenla Scopic Press

Chenla will run it's own unique academic publishing company
called a /scopic press/.

A scopic publication not only includes narrative works that
constitute a traditional book, but all of the surrounding
context of the book which are typically only linked to in
hypertext links (in electronic formats) as well as in
references, footnotes and bibliographies.

The full publication will be in electronic formats that
include all materials as well as an index which can be
imported into a graph database.  Users will then be able to
build personal libraries where works are woven together with
personal notes, correspondence, bookmarks, excerpts and
quotes, works in progress, glosses and other annotations.

Multiple editions will be published with different subsets
of the full scopic texts in both electronic and print that
will more closely resemble traditional books.

Chenla will publish original works, as well as /scopic
editions/ of select works which are deemed important to
realizing Chenla's mandate to build a distributed
civilization.

** Chalkhall
:PROPERTIES:
:ID:       301a4758-d591-4e82-9f7a-c17037c21f0a
:END:

Chalkhall is an ongoing program for rethinking education in
the 21st century.

What we know about the world is constantly changing. Facts
that you learned in school are out of date or just plain
wrong in a decade cite:arbesman:2012half-life

The technology you use today, is already out of date,
development has moved on before you have even heard about
it.

schools are now keeping up with either facts or technology
-- and they are not teaching students how to learn on their
own, or give them the cognitive tools they will need for a
career that is in constant change.

learning can not longer be a place you go, or a time in your
life where you learn what you need for the rest of the your
life.  learning needs to become a habit that you practice
every day, like exercise.

Technology is changing so rapidly that careers will change
dramatically over the course of a lifetime.



** D9D Services

D9D is shorthand for Distributed (9 characters between the
two d's).

D9D Services provide the IT and Networking infrastructure
for everything being done under the Chenla Institure
umbrella.

Services will be divided into four parts:

  - Compute   :: containerized cloud computing services
  - Store     :: digital storage (block, object & filesystem)
  - Cognition :: machine learning services
  - Graph     :: graph database as a service

All services will be provided through the IPFS network, so
that services may be distributed across different, servers,
clusters and cloud providers around the world.

Services will be provided to all Chenla projects.  They will
also be offered free of charge to the larger Chenla
community for hosting projects that are free and open
source, that work towards Chenla's mandate of building a
distributed civilization.  Services will also be provided to
NGOs, colleges & universities for reasearch or providing
online educational courseware that are open and free to the
public.

A commercial spinoff of D9D Services will be provided under
the name /Kinto Cloud Services/ which Chenla will maintain
shares in.

* Facilities

 - Viz Centre : collaboration and conference space
 - Fab Lab    : tool & machine fabrication
 - Map Lab    : content & code
 - Wet Lab    : Gene Splicing & Agricultural Biotech
 - DataCenter : Containerized Process Cluster

Renovation of existing structures @prekleap 
 - exisiting buildings
 - riverfront erosion control & development
 - modular containerized data center
 - solar & gasification electrical generation

Equipment List
 
 - servers and routers
 - converted 20 foot ISO shipping containers

 - CNC milling, router & plasma cutters
 - 3D Printing
 - Metal/Machine Shop
 - Wood Shop
 - Electrical/Electronics Shop     

 - CRSPR gene splicers
 - tissue culture lab
 - 

* People

  - people:
    - faculty 
    - sabbatical program
    - fellowship program
    - internship program
    - tutorial program

* Events & Publications

  - Conferences, Symposia, & Summits
  - Journal, Books -- original works and reprinting
    important works that are crucial to building and
    maintaining a distributed civilization.

* Financial

While we will actively seek our and apply for grants,
relying on grants for funding, or any one source of revenue
is not sustainable.

  - Corporate Sponsorship
  - Endowments
  - Consulting Services
  - In-Kind Donations

