#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Notes on the Institute of Advanced Studies 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Notes on the Institute of Advanced Studies
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/bluebooks/ils-notes.org
  :Created:   2018-06-14T11:30@Prek Leap (11.642600N-104.919210W)
  :ID:        6bd6ad87-ad95-4034-8769-8aafe6b37958
  :VER:       582222670.531536192
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:RWS4-0778
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:


#+begin_quote
Universities, being primarily intellectual in character,
ought to me small and plastic; they should be havens where
scholars, and scientists may regard the world and its
phenomena as their laboratory, without being carried off by
the maelstrom; they should be simple, comforable, quiet
without being monastic or remote; they should be afraid of
no issue; yet they should be under no presure from any side
which might ted to force their scholars to be prejudiced
either for or against any particular solution of the
problems under study; and they should provide the
facilities, the tranquility, and the time requisite to
fundamental inquiry.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  pg.23
#+end_quote

#+begin_quote
The suggestions that the Institute for Advanced Study should
be small, that its staff ad students or scholars should be
few, that administration should be iconspiciouse,
inexpensive, subordinate, that members of the teaching
staff, while freed from the waste of time involved in
administrative work, should freely participate in decesions
involving the character, quality, and direction of its
activities, that living conditions should represent a marked
improvement over contemporary academic conditions in
America, that its subjects should be fundamental in
character, ad that it should develop gradually — on these
suggestions there was on both sides of the Atlantic
unanimous agreement.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  pg.26
#+end_quote

#+begin_quote
Let me now draw a line between the Institute for Advanced
Study, as I conceive it, by reason of its constitution and
conception be a research institute; if the members of its
staff are not contributors to the progress of knowledge and
the solution of problems, there is no sufficient reason for
setting up; but they will also be teachers, men who have
chosen a few competent and earnest disciples engaged in the
mastery of a subject, precisely as the pupils of all the
great masters of the last century...  Teaching should,
however be informal; for, if formal, mechanism will be
devised; its burden should be light, for, if it is heavy,
the teacher has too many pupils or the pupils unfit.  And
the students may at times be investigators too, though not
prematurely at the price of mastering their subjects.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  pg.27
#+end_quote

#+begin_quote
In the so-called "research insitutes" teaching is, of
course, also carried on, though in somewhat different
fashion.  The members of a research institute are also
learners, whatever else they be.  And yet the emphasis is
different, for the research institute is primarily concerned
with problems, very specific problems, as a rule; and young
men enter either as assistants to older workers or as
novices to be tried out by time.  The Institute for Advanced
Stude will be neither a current university, struggling with
diverse tasks and many students, nr a research institute,
devoted soley to the solution of problems.  It may be
pictured as a wedge inserted between the two — a small
university, in which a limited about of teaching and liberal
amount of research are both to be found.  Persons who
require to be drilled or taught hard do not belong within
the Institute for Advanced Study.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  pg.27
#+end_quote

#+begin_quote
The level of teaching and its form mark it off sharply from
college teaching, from most university teaching, from
technological or professional teaching.  This granted, the
professor himself benifits, if for an hour or two weekly, in
addition to his own research and the supervision of a few
investigations, he discusses with a small thoroughly
competent boduy a larger theme.  He is thus assisted in
preserving his own perspective, and he has a motive for
wider reading and broader contacts.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  pg.27
#+end_quote



#+begin_quote
[C]reate a series of schools or groups — a school of
mathematics, a school of economics, a school of history, a
school of philosophy, etc.  The "schools" may change from
time to time; in any event, the designations are so broad
that they may readily cover one group of activities today,
quite another group, as time goes on.  Thus, from the outset
the school of mathematics may well contain the thistory or
philosphy of science; the school of economics, a chair of
law or political theory.  Each school should conduct its
affairs in its own way; for neither the subjects nor the
scholars will all fit into one mould.  An annually changing
chairman would perhaps be the only officer requisite.
There should be complete academic freedom as there is in
England, France and Germany.  We are, let it be remembered,
dealing with seasoned and, I hope, eminent scholars, who
must not be seriously or long diverted from creative work.
These men know their own minds; they have their own ways;
the men who have, throughout human history, meant most to
themselves and to human progress have usually followed their
own inner light; no organizer, or administrator, no
institution can do more than furnish conditions favorable to
the restless prowling of an enlightened and informed human
spirit, seeking its intellectual and spiritual prey.
Standardization and organization do not aid: they are simple
irksome.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  pg.27
#+end_quote

#+begin_quote
I am clear that the relationship between the executive
officers and faculty is not usually in American cordial or
satisfactory.  On the contrary, for one reason or another,
the American professorate is unhappy — andit will not enlist
the country's best brais in sufficient number until the
atmosphere is radically changed.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  pg.28
#+end_quote




** References

https://www.ias.edu/ideas/usefulness-useless-knowledge
https://outline.com/DHRy7P
https://archive.org/details/americancollege03flexgoog
https://www.ias.edu/about/mission-history
https://library.ias.edu/files/pdfs/bulletins/Bulletin1.pdf
https://library.ias.edu/files/pdfs/bulletins/Bulletin9.pdf
https://web.archive.org/web/20160305202831/http://www.cas.uio.no/Publications/Jubilee/History_of_institutes.pdf

https://www.ias.edu/publications
https://www.ias.edu/files/pdfs/publications/establishing-the-ias.pdf

