#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Notes on the Institute of Advanced Studies 
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
#+LINK: pdf   pdfview:~/proj/chenla/hoard/lib/

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-w & w-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

[[[../../index.org][top]]] [[[../index.org][up]]]

* Notes on the Institute of Advanced Studies
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/bluebooks/ils-notes.org
  :Created:   2018-06-14T11:30@Prek Leap (11.642600N-104.919210W)
  :ID:        6bd6ad87-ad95-4034-8769-8aafe6b37958
  :VER:       582222670.531536192
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:RWS4-0778
  :Class:     primer
  :Type:      work
  :Status:    wip
  :Licence:   MIT/CC BY-SA 4.0
  :END:


#+begin_quote
Universities, being primarily intellectual in character,
ought to me small and plastic; they should be havens where
scholars, and scientists may regard the world and its
phenomena as their laboratory, without being carried off by
the maelstrom; they should be simple, comforable, quiet
without being monastic or remote; they should be afraid of
no issue; yet they should be under no presure from any side
which might ted to force their scholars to be prejudiced
either for or against any particular solution of the
problems under study; and they should provide the
facilities, the tranquility, and the time requisite to
fundamental inquiry.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.23]]
#+end_quote

#+begin_quote
The suggestions that the Institute for Advanced Study should
be small, that its staff ad students or scholars should be
few, that administration should be iconspiciouse,
inexpensive, subordinate, that members of the teaching
staff, while freed from the waste of time involved in
administrative work, should freely participate in decesions
involving the character, quality, and direction of its
activities, that living conditions should represent a marked
improvement over contemporary academic conditions in
America, that its subjects should be fundamental in
character, ad that it should develop gradually — on these
suggestions there was on both sides of the Atlantic
unanimous agreement.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.26]]
#+end_quote

#+begin_quote
Let me now draw a line between the Institute for Advanced
Study, as I conceive it, by reason of its constitution and
conception be a research institute; if the members of its
staff are not contributors to the progress of knowledge and
the solution of problems, there is no sufficient reason for
setting up; but they will also be teachers, men who have
chosen a few competent and earnest disciples engaged in the
mastery of a subject, precisely as the pupils of all the
great masters of the last century...  Teaching should,
however be informal; for, if formal, mechanism will be
devised; its burden should be light, for, if it is heavy,
the teacher has too many pupils or the pupils unfit.  And
the students may at times be investigators too, though not
prematurely at the price of mastering their subjects.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.27]]
#+end_quote

#+begin_quote
In the so-called "research insitutes" teaching is, of
course, also carried on, though in somewhat different
fashion.  The members of a research institute are also
learners, whatever else they be.  And yet the emphasis is
different, for the research institute is primarily concerned
with problems, very specific problems, as a rule; and young
men enter either as assistants to older workers or as
novices to be tried out by time.  The Institute for Advanced
Stude will be neither a current university, struggling with
diverse tasks and many students, nr a research institute,
devoted soley to the solution of problems.  It may be
pictured as a wedge inserted between the two — a small
university, in which a limited about of teaching and liberal
amount of research are both to be found.  Persons who
require to be drilled or taught hard do not belong within
the Institute for Advanced Study.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.27]]
#+end_quote

#+begin_quote
The level of teaching and its form mark it off sharply from
college teaching, from most university teaching, from
technological or professional teaching.  This granted, the
professor himself benifits, if for an hour or two weekly, in
addition to his own research and the supervision of a few
investigations, he discusses with a small thoroughly
competent boduy a larger theme.  He is thus assisted in
preserving his own perspective, and he has a motive for
wider reading and broader contacts.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.27]]
#+end_quote



#+begin_quote
[C]reate a series of schools or groups — a school of
mathematics, a school of economics, a school of history, a
school of philosophy, etc.  The "schools" may change from
time to time; in any event, the designations are so broad
that they may readily cover one group of activities today,
quite another group, as time goes on.  Thus, from the outset
the school of mathematics may well contain the thistory or
philosphy of science; the school of economics, a chair of
law or political theory.  Each school should conduct its
affairs in its own way; for neither the subjects nor the
scholars will all fit into one mould.  An annually changing
chairman would perhaps be the only officer requisite.
There should be complete academic freedom as there is in
England, France and Germany.  We are, let it be remembered,
dealing with seasoned and, I hope, eminent scholars, who
must not be seriously or long diverted from creative work.
These men know their own minds; they have their own ways;
the men who have, throughout human history, meant most to
themselves and to human progress have usually followed their
own inner light; no organizer, or administrator, no
institution can do more than furnish conditions favorable to
the restless prowling of an enlightened and informed human
spirit, seeking its intellectual and spiritual prey.
Standardization and organization do not aid: they are simple
irksome.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  pg.27
#+end_quote

#+begin_quote
I am clear that the relationship between the executive
officers and faculty is not usually in American cordial or
satisfactory.  On the contrary, for one reason or another,
the American professorate is unhappy — andit will not enlist
the country's best brains in sufficient number until the
atmosphere is radically changed... and that policies and
measures that are inimical to the happy and enthusiastic
pursuit of learning are necessarily wrong.  It has been
urged that trustees should limit their activities to
business matters and that faculties should goveren all else.

— Abraham Flexner
  Confidential Memorandum to the Trustee (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.28]]
#+end_quote

#+begin_quote
The  schools composing the Insitute sould each select and
admit its own students; no registration office is needed,
for under existing academic conditions in America the
possession of a diploma or degree does not indicate whether
its owner is for or unfot for advanced study.  They must be
discovered by any means calculated to locate them.  Such
students do indeed exist in America in considerable numbers;
but tey are not easily found, for already universities bid
against each other for them either by offering fellowships
freely or by offering part-time employment.  I am sure that
employment as assistant at this stage of the student's
progress is wrong: in a recent report the President of
Harvard delores the fact that of the graduate students of
Harvard University 56% are now "part-time".  I should urge
that students be as a rule full-time...

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  pg.30
#+end_quote

#+begin_quote
No requirements are needed as to the maximum or minimum
number of hours or years that the student must or my work,
neither as to majors or minors requiste to the attainment of
a degree...  There will be excellent students who will work
in one way; equally excellent students who will work quite
differently.  Subjects or fields do not have to be "covered"
— cannot be, at a high level.  In his own time, the students
may show that he has mastered his subject, without which
mastery the Institute should give him no mark of
approval... But in any case the numbers will be so small
that professor and students will know one another
intimately; machinery will be superflous; arrangements
should vary from man to man, from year to year, from subject
to subject. The hightest possible standard of both general
and special education should be insisted on: so much the
founders proposed in their first letter to the Trustees.  

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.30]]
#+end_quote

#+begin_quote
Now there is no question that scholars rely upon on another,
as they reply upon the long history of which they are
endeavoring to forge a new link.  But great scholars,
scientists, and philosphers may be mentioned, who, while
leaning upon the past, did their fundemental thinking along
— Kant, Newton, Faraday, Darwin, Henry, and more recently
Einstein, who as latterly said:

  "I am a horse for single harness, not cut for tandem or
  team work; for well I know that in order to attain any
  definite goal, it is imperitive that _one_ person should
  do the thinking and commanding and carry most of the
  responsibility.  But those that are led should not be
  driven, and they should be allowed to choose their
  leader."

While, therefore, I am of the opinion that the Institure as
a teaching body can probably best function if the
representiives of a given subject meet and discuss their
common interests as a school, I should also allow every
individual and every school group to pursue the methods
that seem to him or them best.  Between men of first-rate
ability collaboration or team work cannot be arranged or
forced; on the other hand, collabortion and dicussion will
take place, where a relatively small group of scholars have
abundent opportunity to discuss with one another either
their own individual problems or problems that lie on the
border line.

In the course of time, the buildings may be so conceieved
and executed as to facilitate intercourse of this type.  I
have in mind the evolution that in the process of centuries
has taken place at All Souls College, Oxford, where, as in
the proposed Institure, there are no undergraduate students,
and where advanced students and the older Fellows live under
ideal conditions,  whether for their own individual work or
for the collaboration and cooperation.  No one planned all
this.  It grew up because scholars were left free to work
out their own salvation.  It can not be imitated or taken
over; but it is there, as evidence that the thing can be
done, if the pace is not forced and if the hand of the
executive and administrator touches but lightly the growing
organism.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.31-32]]
#+end_quote

#+begin_quote
The professor is not in competition with professional or
bussiness life; the income of a budy lawyer or doctor or
business man would harm, not help him.  He must be so
devoted to learning that he would be willing for its sake to
edure hardship and deprivation.  All too frequently he has
done and is doing so.  But it does not follow that, because
riches may harm him, comparative poverty aides him.  His
needs are relatively simple, though, such as they reasonably
are, they should be amply satisfied; and a contributory
pension scheme should be open to all connected to the
University.  It does not help the clarity or concentration
of a man's thinking, if he is oppressed by the fear of a
needy or precarious old age, if on retirement his scale of
living, already non too lavish, has to be suddenly reduced,
if his wife is compelled to forgo domestic help, if his
children are deprived of liberal educational opportunities,
if he lives in cramped quarters, if he lacks privacy, books,
music or travel, if he led either to marry for money r to
forgo the raising of a family, if a gap — social or
financial — exists between the administrative and executive
heads, on the one hand, and the scholar, on the other.  Noe
is the university assisted, if a low scale of renumeration
draws to its staff mainly mediocre or part-time workers,
forced to increase their income by splitting their energy
and attention....  But such a scale of renumeration is not
a one-sided affair; it pledges the professor to devote his
whole time to the university and to avoid gainful
activities.  Should this policy be accepted, as in my
opinion it must, the entire faculty of an American
institution will thus be placed on a full-time basis; real
academic freedom — the freedom to work unworried and
unhampered — will be attained.

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.40]]
#+end_quote

#+begin_quote
A group of scholars should not be isolated; they need access
to libraries, museums, collections, and other scholars — the
more so... If the life of the academic body is to be normal
and wholesome, the accessories of civilization must be
obtainable with such means as they possess — I mean schools,
physicians, friends, and domestic aid.  "Association with
other men like themselves", writes one who has thought
deeply about the project, "will be agreeable and informed by
the interestes and graces of the mind.  Life will be
intensely active, but leisurely at the same time, as
scholars and wise men know how to make life leisurely. If I
am so movws, I cannot doubt that there must be countless
other men who are moved by the same desires."... In time,
certain conditions affecting the site will require
consideration.  It should be large enough to be forever
protected against noise and budtle of urban or commerical
life. 

— Abraham Flexner
  Confidential Memorandum to the Trustees (September 26,1931)
  cite:flexner:1941confidential, [[pdf:flexner:1941confidential.pdf][pg.41]] 
#+end_quote





** References

https://www.ias.edu/ideas/usefulness-useless-knowledge
https://outline.com/DHRy7P
https://archive.org/details/americancollege03flexgoog
https://www.ias.edu/about/mission-history
https://library.ias.edu/files/pdfs/bulletins/Bulletin1.pdf
https://library.ias.edu/files/pdfs/bulletins/Bulletin9.pdf
https://web.archive.org/web/20160305202831/http://www.cas.uio.no/Publications/Jubilee/History_of_institutes.pdf

https://www.ias.edu/publications

- Flexner, A., Confidential memorandum to the trustees, In
  (Eds.), Establishing the IAS (pp. ) (1941). : Institute of
  Advanced Study.  cite:flexner:1941confidential
